dist: trusty
sudo: false

language: node_js
node_js:
  - node

env:
  global:
    - MOZ_HEADLESS=1

addons:
  chrome: stable
  firefox: latest

cache:
  directories:
    - ./node_modules

install:
  - npm install

before_script:
  - npm install -g @angular/cli

script:
  - ng build
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox --code-coverage

after_script:
  - cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  skip-cleanup: true
  provider: firebase
  #Note: this is just for testing right now
  on:
    branch: Develop
  token:
    secure: $FIREBASE_TOKEN
